### ISSUE TITLE
規定ブラウザ設定

### ISSUE THREAD

**Issue by n-inja** [traPtitech/traQ-iOS#11]
wiki等のリンク、メッセージ中のリンクのURLスキームを変更できるようにする

関連 https://github.com/traPtitech/traQ-UI/issues/1034

**Comment by Eleven-Lines** [comment]
動線としては

- 設定アプリから
- 初回選択時に選ばせる

あたりがありそう

**Comment by tohutohu** [comment]
あ〜設定アプリから開く画面にUIをもたせられるのか、それならそれがUIとの連携を考えなくていいからいいと思う

初回選択時に選ばせるのは、ネイティブアプリのUIを書ける人がいるならやるのも良さそう(僕はモチベーションがないです)

**Comment by sapphi-red** [comment]
iOS14でデフォルトブラウザが設定できるようになるのでクローズ
