### ISSUE TITLE
設定モーダルが開かない

### ISSUE THREAD

**Issue by logica0419** [traPtitech/traQ-iOS#24]
https://q.trap.jp/messages/bc54dd3b-3688-41e7-a565-eb2d8025d77b
https://q.trap.jp/messages/79bd1ba8-59c3-409a-b992-51c4869562ec
設定モーダルのアイコンをクリックしても何も表示されないです。設定がリセットされているケースも。

**Comment by sapphi-red** [comment]
Safariでは発生せずアプリでのみ発生

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/traQ_S-UI/commit/e906ae7a7663c79069c17c8dd6b1e69c931d84d8 で修正
