### ISSUE TITLE
traQで起きてるiOSがらみの問題たちの調査

### ISSUE THREAD

**Issue by logica0419** [traPtitech/traQ-iOS#25]
https://github.com/traPtitech/traQ_S-UI/issues/646
https://github.com/traPtitech/traQ_S-UI/issues/886
https://github.com/traPtitech/traQ_S-UI/issues/2088
traQ-S UIのissueに書かれているのはこの3件
アプリ内で何か不都合が起こっていないか調査が必要か？

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/traQ_S-UI/issues/2088 だけになったのでクローズ
