### ISSUE TITLE
グループ管理が開かない

### ISSUE THREAD

**Issue by logica0419** [traPtitech/traQ-iOS#27]
#24 
設定モーダルと同じような現象がグループ管理画面でも起こることが確認できました

**Comment by sapphi-red** [comment]
Safariでは発生せずアプリでのみ発生

**Comment by sapphi-red** [comment]
https://github.com/traPtitech/traQ_S-UI/commit/e906ae7a7663c79069c17c8dd6b1e69c931d84d8 で修正
